q.vermelhodo.mktl.device.updateSrcDstAddr( "127.0.0.1", 57121 );
// q.vermelhodo2.mktl.device.updateSrcAddr( "127.0.0.1", 57123 );
q.laranjare.mktl.device.updateSrcAddr("127.0.0.1", 57122 );
q.amarelomi.mktl.device.updateSrcAddr( "127.0.0.1", 57123 );
q.verdefa.mktl.device.updateSrcAddr( "127.0.0.1", 57124 );
// q.verdefa2.mktl.device.updateSrcAddr( "127.0.0.1", 57127 );
q.verdesol.mktl.device.updateSrcAddr( "127.0.0.1", 57125 );
q.lilassi.mktl.device.updateSrcAddr( "127.0.0.1", 57126 );